<?php

/**
 * @file gridster.module
 */

/**
 * Implements hook_ctools_plugin_directory()
 */
function gridster_ctools_plugin_directory($module, $plugin) {
  if ('panels' === $module) {
    switch ($plugin) {
      case 'styles':
        return 'plugins/' . $plugin;
    }
  }
}

/**
 * Implements hook_library()
 */
function gridster_library() {
  $base = drupal_get_path('module', 'gridster');

  $libraries['gogridster'] = array(
    'title' => '[AngularJS] GoGridster',
    'website' => 'http://www.go1.com.au/',
    'version' => VERSION,
    'js' => array(
      "$base/misc/gogridster/angular-gridster/angular-gridster.js" => array(),
      "$base/misc/gogridster/gogridster/gogridster.js" => array(),
      "$base/misc/gogridster.js" => array(),
    ),
    'css' => array(
      "$base/misc/gogridster/angular-gridster/angular-gridster.css" => array(),
    ),
    'dependencies' => array(
      array('system', 'ui.resizable'),
      array('system', 'ui.draggable'),
      array('angularjs', 'angularjs')
    ),
  );

  return $libraries;
}

/**
 * Implements hook_forms()
 *
 * @param string $form_id
 * @param array $args
 * @return array
 */
function gridster_forms($form_id, $args) {
  $forms = array();

  if (0 === strpos($form_id, 'gridster_panel_region_config_form_')) {
    $forms[$form_id]['callback'] = 'gridster_panel_region_config_form';
  }

  return $forms;
}
